### ISSUE TITLE
Proposal: Better Query Capabilities

### ISSUE THREAD

**Issue by KallynGowdy** [casual-simulation/aux#8]
This is a proposal for adding more comprehensive query capabilities to the scripting API.

Currently, it is possible to query bots by a single tag and value but it is cumbersome to find bots based on two or more different tags. To perform such a query would require manually filtering bots.

I suggest we add support for the following syntax:

```javascript
// Get a list of bots with both of the given tags
let results = getBots(
  byTag("tagA", "valueA"),
  byTag("tagB", "valueB")
);

// Get a list of bots with a tag that matches the given predicate
let results = getBots(
  byTag("tagA", val => val === 5  || val === 3)
);

// Get a list of bots with either of the given tags
let results = getBots(
  either(byTag("tagA", "valueA"), byTag("tagB", "valueB"))
);

// Get a list of bots in a context
let results = getBots(
  inContext("context")
);

// Get a list of bots by custom filter functions
let results = getBots(
  bot => getTag(bot, "tagA") === "valueA",
  bot => getTag(bot, "tagB") > 0
);
```

This means adding the following functions:

- `byTag(tag, value/tag predicate) -> bot predicate` - a [higher order function][hof] which accepts a tag and a value/predicate and returns a function which determines if a given bot matches the tag and value.
- `inContext(context) -> bot predicate` - a [higher order function][hof] which accepts a context ID and returns a function that determines if a given bot is in the context.
- `inStack(bot, context) -> bot predicate` - a [higher order function][hof] which accepts a bot and a context ID and returns a function that determines if a given bot is in the same stack as the original bot.
- `neighboring(bot, context, direction) -> bot predicate` - a [higher order function][hof] which accepts a bot, context ID, and direction and returns a function that determines if a given bot is neighboring the original bot.
- `either(predicate1, predicate2) -> bot predicate` - a [higher order function][hof] that accepts two or more predicates and returns a function which determines if any of the given predicates return true for a bot.

It also means modifying the following functions:

- `getBots()` will be modified to accept a variable number of predicate functions that will be used as a way to filter bots. The current `getBots("tag", "value")` syntax will be preserved and the new form will only take effect if the first parameter is a function.
- `getBot()` will be modified to accept the same parameters that `getBots()` does and will return the same results with the condition that `getBot()` always returns the first result or null.

After these changes, the following functions become redundant:

- `getBotsInContext(context)` would become `getBots(inContext(context))`
- `getBotsInStack(bot, context)` would become `getBots(inStack(bot, context))`
- `getNeighboringBots(bot, context, direction)` would become `getBots(neighboring(bot, context, direction))`

[hof]: https://medium.com/javascript-scene/higher-order-functions-composing-software-5365cf2cbe99

**Comment by tomyeti** [comment]
Sounds good to me. What can we do with a predecate outside of a getBots argument? It's an enumerable?

**Comment by tomyeti** [comment]
To add, i think the English language style syntax will be helpful to newcommers but intermediate code learners may be confused by how that actually works. I'm sure they'll get over it. 

We have "and" and "or", how do we handle xor? Can we do inverted byTag? Nand?

**Comment by KallynGowdy** [comment]
@tomyeti  Its a function so you would be able to use it as a filter function if you wanted.

ex.
```javascript
let list = [this, that]; // bots list
let filtered = list.filter(byTag("abc", "def"));
```

In the future we might short-circuit some filters to instead do a lookup on an index instead of checking each file individually but that won't change the semantics.

On the topic of logical operators I'm not sure how much XOR or NAND are needed at this point. I think part of the reasoning behind letting you use your own functions is that if you want to get into that sort of stuff you can without waiting on us to make a helper for that. I do think that a `not` function would be helpful though.

**Comment by jfreeney** [comment]
I like this @KallynGowdy let's do it and get rid of the dupe functions.
